/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.vo.OpBinaria;
import com.vo.JConversion;
import javax.swing.JOptionPane;

/**
 *
 * @author LINUX
 */
public class JCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JCalculadora
     */
    public JCalculadora() {
        initComponents();
        setLocationRelativeTo(null);
        PanelA.setVisible(false);
        JPanelOperaciones.setVisible(false);
        JPanelConversiones.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        PanelA = new javax.swing.JPanel();
        JPanelOperaciones = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        tbxNumA = new javax.swing.JTextField();
        tbxNumB = new javax.swing.JTextField();
        tbxNumRes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JPanelConversiones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jconvertirA = new javax.swing.JTextField();
        jconvertirRes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        JOpciones = new javax.swing.JMenu();
        JOperaciones = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel5.setFont(new java.awt.Font("News Gothic", 0, 11)); // NOI18N
        jLabel5.setText("Operaciones con binarios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Binaria");
        setPreferredSize(new java.awt.Dimension(630, 367));

        PanelA.setBackground(new java.awt.Color(255, 255, 255));
        PanelA.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JPanelOperaciones.setBackground(new java.awt.Color(102, 153, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suma", "Resta", "División", "Multiplicación" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tbxNumA.setText("0");
        tbxNumA.setToolTipText("Número");
        tbxNumA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxNumAKeyReleased(evt);
            }
        });

        tbxNumB.setText("0");
        tbxNumB.setToolTipText("Número");
        tbxNumB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxNumBKeyReleased(evt);
            }
        });

        tbxNumRes.setText("0");
        tbxNumRes.setToolTipText("Resultado");

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/java.gif"))); // NOI18N

        jLabel7.setText("Operaciones con binarios");

        javax.swing.GroupLayout JPanelOperacionesLayout = new javax.swing.GroupLayout(JPanelOperaciones);
        JPanelOperaciones.setLayout(JPanelOperacionesLayout);
        JPanelOperacionesLayout.setHorizontalGroup(
            JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelOperacionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelOperacionesLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPanelOperacionesLayout.createSequentialGroup()
                        .addGroup(JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxNumRes, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(tbxNumB)
                            .addComponent(tbxNumA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        JPanelOperacionesLayout.setVerticalGroup(
            JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelOperacionesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxNumA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelOperacionesLayout.createSequentialGroup()
                        .addGroup(JPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelOperacionesLayout.createSequentialGroup()
                                .addComponent(tbxNumB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(tbxNumRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelOperacionesLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        JPanelConversiones.setBackground(new java.awt.Color(102, 153, 255));
        JPanelConversiones.setPreferredSize(new java.awt.Dimension(498, 260));

        jButton2.setText("Convertir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binario a Decimal", "Octal a Decimal", "Hexadecimal a Decimal", "Decimal a Binario", "Decimal a Octal","Decimal a Hexadecimal","Binario a Hexadecimal","Hexadecimal a Binario","Binario a Octal","Octal a Binario" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jconvertirA.setText("0");
        jconvertirA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jconvertirAKeyReleased(evt);
            }
        });

        jconvertirRes.setText("0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/java.gif"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("News Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Conversiones numericas");

        javax.swing.GroupLayout JPanelConversionesLayout = new javax.swing.GroupLayout(JPanelConversiones);
        JPanelConversiones.setLayout(JPanelConversionesLayout);
        JPanelConversionesLayout.setHorizontalGroup(
            JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConversionesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelConversionesLayout.createSequentialGroup()
                        .addGroup(JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jconvertirRes, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jconvertirA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        JPanelConversionesLayout.setVerticalGroup(
            JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelConversionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jconvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelConversionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jconvertirRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout PanelALayout = new javax.swing.GroupLayout(PanelA);
        PanelA.setLayout(PanelALayout);
        PanelALayout.setHorizontalGroup(
            PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelALayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(JPanelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelALayout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(JPanelConversiones, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );
        PanelALayout.setVerticalGroup(
            PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelALayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(JPanelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelALayout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(JPanelConversiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        jMenuBar.setBackground(new java.awt.Color(102, 153, 255));
        jMenuBar.setBorder(null);
        jMenuBar.setToolTipText("");

        JOpciones.setText("Opciones");
        JOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOpcionesActionPerformed(evt);
            }
        });

        JOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/file 3.png"))); // NOI18N
        JOperaciones.setMnemonic('o');
        JOperaciones.setText("Operaciones");
        JOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOperacionesActionPerformed(evt);
            }
        });
        JOpciones.add(JOperaciones);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/flag.png"))); // NOI18N
        jMenuItem1.setText("Conversiones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JOpciones.add(jMenuItem1);

        jMenuBar.add(JOpciones);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JOpcionesActionPerformed

    private void JOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOperacionesActionPerformed
        // TODO add your handling code here:
        JPanelOperaciones.setVisible(true);
        JPanelConversiones.setVisible(false);

        PanelA.setVisible(true);
    }//GEN-LAST:event_JOperacionesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PanelA.setVisible(true);
        JPanelConversiones.setVisible(true);
        JPanelOperaciones.setVisible(false);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (jComboBox2.getSelectedItem().equals("Binario a Decimal")) {
                jconvertirRes.setText(JConversion.BinarioADecimal(jconvertirA.getText()));
            }
            if (jComboBox2.getSelectedItem().equals("Octal a Decimal")) {
                jconvertirRes.setText(JConversion.OctalADecimal(jconvertirA.getText()));
            }
            if (jComboBox2.getSelectedItem().equals("Hexadecimal a Decimal")) {
                jconvertirRes.setText(JConversion.HexaADecimal(jconvertirA.getText()));
            }
            if (jComboBox2.getSelectedItem().equals("Decimal a Binario")) {
                jconvertirRes.setText(JConversion.DecimalABinario(jconvertirA.getText()));
            }
            if (jComboBox2.getSelectedItem().equals("Decimal a Octal")) {
                jconvertirRes.setText(JConversion.DecimalAOctal(jconvertirA.getText()));
            }
            if (jComboBox2.getSelectedItem().equals("Decimal a Hexadecimal")) {
                jconvertirRes.setText(JConversion.DecimalAHexa(jconvertirA.getText().toUpperCase()));
            }

            if (jComboBox2.getSelectedItem().equals("Binario a Hexadecimal")) {
                jconvertirRes.setText(JConversion.BinarioAHexa(jconvertirA.getText().toUpperCase()));
            }

            if (jComboBox2.getSelectedItem().equals("Hexadecimal a Binario")) {
                jconvertirRes.setText(JConversion.HexaABinario(jconvertirA.getText().toUpperCase()));
            }

            if (jComboBox2.getSelectedItem().equals("Binario a Octal")) {
                jconvertirRes.setText(JConversion.BinariAOctal(jconvertirA.getText().toUpperCase()));
            }

            if (jComboBox2.getSelectedItem().equals("Octal a Binario")) {
                jconvertirRes.setText(JConversion.OctalABinari(jconvertirA.getText().toUpperCase()));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void CleanFields() {
        tbxNumA.setText("0");
        tbxNumB.setText("0");
        tbxNumRes.setText("0");
        jconvertirA.setText("0");
        jconvertirRes.setText("0");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        if (jComboBox1.getSelectedItem().equals("Suma")) {
            tbxNumRes.setText(OpBinaria.Suma(tbxNumA.getText(), tbxNumB.getText()));
        }
        if (jComboBox1.getSelectedItem().equals("Resta")) {
            if(Integer.parseInt(tbxNumA.getText(), 2) < Integer.parseInt(tbxNumB.getText(), 2)){
                 JOptionPane.showMessageDialog(null, "Para esta resta debe usar complemento A1", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                 CleanFields();
            }else{
                tbxNumRes.setText(OpBinaria.Resta(tbxNumA.getText(), tbxNumB.getText()));
            }
        }
        if (jComboBox1.getSelectedItem().equals("División") && !tbxNumB.getText().equals("0")) {
            tbxNumRes.setText(OpBinaria.Divicion(tbxNumA.getText(), tbxNumB.getText()));
        }
        if (jComboBox1.getSelectedItem().equals("Multiplicación")) {
            tbxNumRes.setText(OpBinaria.Multiplicacion(tbxNumA.getText(), tbxNumB.getText()));
        }
         } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbxNumAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxNumAKeyReleased
        // TODO add your handling code here:
        String texto = tbxNumA.getText();
        char[] fuente = texto.toCharArray();
        char[] resultado = new char[fuente.length];
        int j = 0;
        boolean error = false;
        for (int i = 0; i < fuente.length; i++) {

            if (fuente[i] >= '0' && fuente[i] <= '1') {
                resultado[j++] = fuente[i];
            } else {
                error = true;
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
        if (error) {
            tbxNumA.setText(new String(resultado, 0, j));
        }
    }//GEN-LAST:event_tbxNumAKeyReleased

    private void tbxNumBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxNumBKeyReleased
        // TODO add your handling code here:
        String texto = tbxNumB.getText();
        char[] fuente = texto.toCharArray();
        char[] resultado = new char[fuente.length];
        int j = 0;
        boolean error = false;
        for (int i = 0; i < fuente.length; i++) {

            if (fuente[i] >= '0' && fuente[i] <= '1') {
                resultado[j++] = fuente[i];
            } else {
                error = true;
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
        if (error) {
            tbxNumB.setText(new String(resultado, 0, j));
        }
    }//GEN-LAST:event_tbxNumBKeyReleased

    private void jconvertirAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jconvertirAKeyReleased
        // TODO add your handling code here:
        String texto = jconvertirA.getText();
        char[] fuente = texto.toCharArray();
        char[] resultado = new char[fuente.length];
        int j = 0;
        boolean error = false;
        if (jComboBox2.getSelectedItem().equals("Binario a Decimal") || jComboBox2.getSelectedItem().equals("Binario a Hexadecimal")
                || jComboBox2.getSelectedItem().equals("Binario a Octal")) {
            for (int i = 0; i < fuente.length; i++) {

                if (fuente[i] >= '0' && fuente[i] <= '1') {
                    resultado[j++] = fuente[i];
                } else {
                    error = true;
                    java.awt.Toolkit.getDefaultToolkit().beep();
                }
            }
        }
        if (jComboBox2.getSelectedItem().equals("Octal a Decimal") || jComboBox2.getSelectedItem().equals("Octal a Binario")) {
            for (int i = 0; i < fuente.length; i++) {

                if (fuente[i] >= '0' && fuente[i] <= '7') {
                    resultado[j++] = fuente[i];
                } else {
                    error = true;
                    java.awt.Toolkit.getDefaultToolkit().beep();
                }
            }
        }
        if (jComboBox2.getSelectedItem().equals("Hexadecimal a Decimal") || jComboBox2.getSelectedItem().equals("Hexadecimal a Binario")) {
            for (int i = 0; i < fuente.length; i++) {

                if ((fuente[i] >= '0' && fuente[i] <= '9') || fuente[i] == 'A'
                        || fuente[i] == 'B' || fuente[i] == 'C' || fuente[i] == 'D'
                        || fuente[i] == 'E' || fuente[i] == 'F') {
                    resultado[j++] = fuente[i];
                } else {
                    error = true;
                    java.awt.Toolkit.getDefaultToolkit().beep();
                }
            }
        }
        if (jComboBox2.getSelectedItem().equals("Decimal a Binario")
                || jComboBox2.getSelectedItem().equals("Decimal a Octal")
                || jComboBox2.getSelectedItem().equals("Decimal a Hexadecimal")) {
            for (int i = 0; i < fuente.length; i++) {

                if (fuente[i] >= '0' && fuente[i] <= '9') {
                    resultado[j++] = fuente[i];
                } else {
                    error = true;
                    java.awt.Toolkit.getDefaultToolkit().beep();
                }
            }
        }
        if (error) {
            jconvertirA.setText(new String(resultado, 0, j));
        }
    }//GEN-LAST:event_jconvertirAKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        CleanFields();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        CleanFields();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCalculadora().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JOpciones;
    private javax.swing.JMenuItem JOperaciones;
    private javax.swing.JPanel JPanelConversiones;
    private javax.swing.JPanel JPanelOperaciones;
    private javax.swing.JPanel PanelA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jconvertirA;
    private javax.swing.JTextField jconvertirRes;
    private javax.swing.JTextField tbxNumA;
    private javax.swing.JTextField tbxNumB;
    private javax.swing.JTextField tbxNumRes;
    // End of variables declaration//GEN-END:variables
}
